### ISSUE TITLE
Copper slabs/stairs weather into vanilla placements

### ISSUE THREAD

**Issue by SugarDaddii** [FirEmerald/AdditionalPlacements#12]
First: When you place a vertical copper slab  it will rotate back to a normal slab when it oxidise.
         Its on all copper blocks also on stairs. Vertical stairs will go back to normal!

Second: You cant wax vertical copper stuff.

**Comment by FirEmerald** [comment]
Fixed as of [a12fe917237710f159be31fd2ec6ddc6e5aa9dc7](https://github.com/FirEmerald/AdditionalPlacements/commit/a12fe917237710f159be31fd2ec6ddc6e5aa9dc7) and [69c4cb6b849ec4f3f2e2a9213d684b2d4be44620](https://github.com/FirEmerald/AdditionalPlacements/commit/69c4cb6b849ec4f3f2e2a9213d684b2d4be44620)
