### ISSUE TITLE
Macaws Roofs & Roofs BOP Addon invalid for additional placements

### ISSUE THREAD

**Issue by SugarDaddii** [FirEmerald/AdditionalPlacements#13]
These two Mods have roofs labeled as stairs, so your mod try to do its stuff.
But when placing it will become very hard when nothing is below the Roof Block & Vertical roofs are complety destroyed texturewise!

Also the Roofs are only half of a block so your placing grid is very hard to handle asspecially on flat roofs.

So maybe have a modblacklist will help?

**Comment by FirEmerald** [comment]
Implemented as of [b5135923d3dd541c9aa754cf4c6891d1b8b88748](https://github.com/FirEmerald/AdditionalPlacements/commit/b5135923d3dd541c9aa754cf4c6891d1b8b88748) and [79a70aaf43174b620fd08676283075b544bce685](https://github.com/FirEmerald/AdditionalPlacements/commit/79a70aaf43174b620fd08676283075b544bce685)
