### ISSUE TITLE
[1.18.2+1.19.2] Mod Compatibility with Pigsteel

### ISSUE THREAD

**Issue by Thombias** [FirEmerald/AdditionalPlacements#14]
If possible it would be cool to have compatibility with the Pigsteel mod: https://www.curseforge.com/minecraft/mc-mods/pigsteel-forge
This mod adds a material to the nether that uses forge:iron_ingot & forge:iron_nugget for its item tags to function sort of like a nether iron. What makes this mod unique is that you can craft blocks of pigsteel & cut pigsteel blocks that "zombify" like how piglins or hoglins zombify if they happen to be in the overworld. The process is similar to how copper oxidizes in 4 stages using randomtickspeed.
I tested both your mod and pigsteel but unfortunately it requires native support for pigsteel blocks to zombify when placing the slabs or stairs sideways.

**Comment by FirEmerald** [comment]
Implemented as of [8564730993a070eea9f082b61c8b3dd9a988ade5](https://github.com/FirEmerald/AdditionalPlacements/commit/8564730993a070eea9f082b61c8b3dd9a988ade5) and [89a93666ba822708e62922a8eee2e4fbc3a3cab2](https://github.com/FirEmerald/AdditionalPlacements/commit/89a93666ba822708e62922a8eee2e4fbc3a3cab2) which should also solve this problem for any other modded weathering blocks as well.

**Comment by Thombias** [comment]
Awesome! Thank you so much! :)
