### ISSUE TITLE
Splash Partical not Correct when jumping on Additional Placement Blocks

### ISSUE THREAD

**Issue by SugarDaddii** [FirEmerald/AdditionalPlacements#16]
![image](https://user-images.githubusercontent.com/16927094/200712170-9add2a48-2565-4576-abe7-7287ee5258df.png)

**Comment by FirEmerald** [comment]
(edited OP to directly show the image instead of an imgur link)

**Comment by FirEmerald** [comment]
I am unable to reproduce this bug. It's possible one of your mods is at fault.

**Comment by FirEmerald** [comment]
So the way the particle texture is grabbed involves grabbing the particle texture from the model for the base block - check if the original slab has a particle texture. If it also doesn't that's why.

**Comment by SugarDaddii** [comment]
https://i.imgur.com/1ngfznT.png

**Comment by SugarDaddii** [comment]
![Bild_2022-11-09_160939845](https://user-images.githubusercontent.com/14795020/200866909-4bab9d1a-fd1b-44f3-bed1-b671c981a453.png)
Verical dont have :(

**Comment by FirEmerald** [comment]
I am unable to reproduce this issue. It's possible it relates to another mod you are using. If you manage to identify which mod combination causes this, let me know and I'll look into it further.
