### ISSUE TITLE
[Suggestion] Keybind to toggle additional placement on/off

### ISSUE THREAD

**Issue by SugarDaddii** [FirEmerald/AdditionalPlacements#18]
Hey in your Discord a User called Nostalgion was asking for a Keybind to toggle your placement with the Vanilla one on demand!
Is thats even possible?

Have a great day!

**Comment by FirEmerald** [comment]
Theoretically, it's possible, but requires the use of networking to synchronize the keybind state with the server, so I don't currently plan to implement it.

**Comment by LeoBeliik** [comment]
would you accept a pr for this?

**Comment by FirEmerald** [comment]
potentially, if it's actually well implemented. placement keybinds are a lot more involved than just "check if a key is down".

**Comment by FirEmerald** [comment]
Implemented as of:
Forge 1.16.5: 48baf88
Forge 1.18.2: b55dc74
Fabric 1.18.2: 9f943d3
Forge 1.19.2: 248131b
Fabric 1.19.2: 5de479f
Forge 1.19.4: cf623a5
Forge 1.20.1: e11e53a
Fabric 1.20.1: c7eb138
Forge 1.20.2: edb6c47
Fabric 1.20.2: 736f8a5
