### ISSUE TITLE
Error on breaking powered pressure plates

### ISSUE THREAD

**Issue by Zygahedron** [FirEmerald/AdditionalPlacements#22]
```
java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=faci
ng, clazz=class net.minecraft.core.Direction, values=[up, north, south, west, east]
} as it does not exist in Block{minecraft:air}
```
If the player directly causes the pressure plate to be broken (or a supporting block), this just stops block updates from propagating past that point. If the pressure plate is broken for some other reason, the game simply crashes. This seems to be caused by trying to remove redstone power from nearby blocks, which depends on what surface the pressure plate is on... but if the pressure plate doesn't exist anymore, then it's not on any surface. I'm sure somewhere in the processing of breaking the block you have access to the state that it *had*...?

**Comment by FirEmerald** [comment]
fixed as of [cd92977e554ea494761c89b260e392964c26a886](https://github.com/FirEmerald/AdditionalPlacements/commit/cd92977e554ea494761c89b260e392964c26a886) and [3e8c678d5c7e88e0b77a262e570f06b9a0b2a805](https://github.com/FirEmerald/AdditionalPlacements/commit/3e8c678d5c7e88e0b77a262e570f06b9a0b2a805)
