### ISSUE TITLE
Incorrect shading with smooth lighting

### ISSUE THREAD

**Issue by Zygahedron** [FirEmerald/AdditionalPlacements#23]
![image](https://user-images.githubusercontent.com/25967694/209278765-a7722f2d-e516-48fd-81ad-fb62a49c0e35.png)
This affects all relevant blocks, but is especially noticeable with carpets.

**Comment by FirEmerald** [comment]
I've been trying to figure this one out for a while. It's an issue in the ambient occlusion - it's pulling the values from the wrong spots. My original thought was it was an issue with the transformed quads, but that doesn't _seem_ to be the case at least.

**Comment by FirEmerald** [comment]
I haven't seen this issue in a while so I think it's fixed.
