### ISSUE TITLE
Port to Fabric

### ISSUE THREAD

**Issue by Landrozaum** [FirEmerald/AdditionalPlacements#24]
This mod can be ported to fabric? Any plans?

**Comment by FirEmerald** [comment]
It was originally planned but I couldn't get a shared dev workspace to function. I still want to, it's just on the backburner for now.

**Comment by FirEmerald** [comment]
Files are uploaded to curse, pending approval of the project (you will get 404 until then):
https://www.curseforge.com/minecraft/mc-mods/additional-placements-fabric
and the branches are at:
https://github.com/FirEmerald/AdditionalPlacements/tree/1.18.2-fabric
https://github.com/FirEmerald/AdditionalPlacements/tree/1.19.2-fabric
https://github.com/FirEmerald/AdditionalPlacements/tree/1.20.1-fabric
