### ISSUE TITLE
Incorrect shadow textures when Smooth Lighting is turned on

### ISSUE THREAD

**Issue by DiveIntoMadness** [FirEmerald/AdditionalPlacements#25]
When this mod is active and Smooth Lighting is turned on (both at minimum and maximum settings), some blocks have weird shadow textures. Seems to not be affected by whether the block was placed or randomly generated. The bug is most noticeable in dark areas like caves, at night, or in the Nether and on certain blocks like gravel, granite, andesite, and netherrack. Will need more testing to figure out all the blocks affected but these are the ones I've seen so far. 

**Smooth Lighting off:**
![image](https://user-images.githubusercontent.com/123724605/215041245-341c91f0-5837-4a87-a9f2-daf05ff9fab9.png)

**Smooth Lighting at either Minimum or Maximum:**
![image](https://user-images.githubusercontent.com/123724605/215041290-5482652f-db13-47de-87ac-bacaa5ab6fe9.png)

**Smooth Lighting on, granite placed by player:**
![image](https://user-images.githubusercontent.com/123724605/215044062-304f68b3-be3f-4e3b-997f-b850c5eef861.png)

**Comment by FirEmerald** [comment]
I think you have the wrong mod - this mod makes absolutely no changes to the lighting engine. Everything mostly runs on the existing rendering code as it is. Additionally, I am unable to reproduce this bug, and it's clear you have other mods installed. Please ensure before posting bugs that you either aren't using other mods, or that the issue specifically occurs _only_ when this mod is installed alongside another mod(s) and provide the name of that mod(s). Additionally, you should always mention which minecraft version you are using.
