### ISSUE TITLE
Crash on 1.18.2

### ISSUE THREAD

**Issue by Aceplante2** [FirEmerald/AdditionalPlacements#27]
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property EnumProperty{name=type, clazz=class net.minecraft.world.level.block.state.properties.SlabType, values=[top, bottom, double]} as it does not exist in Block{additionalplacements:minecraft.oak_slab}

the only other mod im using thats slab related is kree slabs.

**Comment by FirEmerald** [comment]
Kree Slabs and Additional Placements are _not_ compatible with each other.

**Comment by Aceplante2** [comment]
Ah, fair enough thank you
