### ISSUE TITLE
Possible incompatibility with Create

### ISSUE THREAD

**Issue by ranenvious** [FirEmerald/AdditionalPlacements#30]
I'm trying to use vertical stone brick slabs in one of my Create contraptions, but for some reason whenever I do the contraption anchor itself (a mechanical sticky piston in this case) claims that it can't create a contraption because there is an immovable block at the exact coordinates I'm building at, with the y level inverted. In other words, if the slab is at 400, 61, 300, it will complain that there is unmovable deepslate at 400, -61, 300. 
This could be an issue on Create's end, it could be another issue entirely, but given it's only happening the the vertical slabs whereas every other part of the contraption builds fine I do think it's an issue with this mod having a conflict with Create 

edit : forgot details, forge 19.2, most recent version of forge, create 5.1, and most recent version of additional placements

**Comment by FirEmerald** [comment]
I was unable to replicate this behavior in my workspace. could you share some screenshots of the contraption in question, and ensure the vertical slab in question is actually one from this mod and not another mod providing similar functionality?

**Comment by FirEmerald** [comment]
closing the issue due to inactivity.
