### ISSUE TITLE
Breaking blocks takes ages

### ISSUE THREAD

**Issue by Lux-Studios** [FirEmerald/AdditionalPlacements#31]
When breaking a vertical slab or stair, there's no difference between using different tools, and on top of that, stairs (at least deepslate ones) don't drop anything after being broken.

Please fix.

**Comment by FirEmerald** [comment]
it's not broken. You need to follow the instructions that _should_ have been given when you logged in and run /ap_tags_export and then /reload (or reload the world if cheats are disabled) to generate the tags for the blocks, which control block breaking logic.
