### ISSUE TITLE
1.18.2 sideways stairs don't break properly

### ISSUE THREAD

**Issue by GrandmaPork** [FirEmerald/AdditionalPlacements#33]
If you place sideways wooden stairs, they break as if you were punching them even if you're using an axe. Same thing for stone-based stairs. Even if you have a pickaxe, they break as if you were punching them.

**Comment by FirEmerald** [comment]
for gods sake, this is a **user error.** see https://github.com/FirEmerald/AdditionalPlacements/issues/31

**Comment by GrandmaPork** [comment]
Lmao my b
