### ISSUE TITLE
Inventory Actions & Additional Placements

### ISSUE THREAD

**Issue by dadoirie** [FirEmerald/AdditionalPlacements#34]
any idea why Inventory Actions (https://www.curseforge.com/minecraft/mc-mods/inventory-actions) and Additional Placements conflicting here and if this can be fixed without limiting either of both mods capabilities?
I assume blacklisting the copper slabs & stairs for additional placement might be doing the trick here, but then this has to be done with any item I'm creating possible inventory action ... or could a compat fix be made between them?

https://mclo.gs/eAYTgZa

starting at Line 217: https://mclo.gs/eAYTgZa#L217

took me quite a few hours finding this conflict from a 243 mods list (and growing) and I really hope a compat is possible, because both mods are very desired

it doesn't crash, just makes any material additional placement is using inventory actions can't do nothing with it

**Comment by FirEmerald** [comment]
This is an issue on InventoryAction's end - they are converting <Block, Block> pairings to <Item, Item> pairings without accounting for the possibility of multiple pairings using the same item form. I will forward this issue to them.
