### ISSUE TITLE
Unable to break vertical stairs

### ISSUE THREAD

**Issue by emma-1075** [FirEmerald/AdditionalPlacements#35]
Each respective tool doesnt work on its respective materials. One Probe labels it as needing no tool, and I can hit it with stuff long enough that it breaks, but it acts as if im breaking it with my hands, and certain blocks ( ie vert cut copper stairs) dont't drop after breaking. 

[screen-capture.webm](https://github.com/FirEmerald/AdditionalPlacements/assets/136605256/94741e9b-046b-4d2a-883a-7b5723321db4)

in the clip i'm using the wand of symmetry from create, but i recreated the issue without it active
currently installed includes create, several create add-ons, a diff vert slabs mod (it creates new items), redstone addition mods, dummy, mouse tweaks, rubidium+oculus, ferritecore, some worldgen stuff like yung's series, chipped, domum ornamentum, building wands, toolbelt, several elytra tweaks, wither skelly tweaks, and more but idk which ones would be relevant

**Comment by FirEmerald** [comment]
ISTG. https://github.com/FirEmerald/AdditionalPlacements/issues/31
