### ISSUE TITLE
Advanced Placement blocks missing Block tags

### ISSUE THREAD

**Issue by Xefyr0** [FirEmerald/AdditionalPlacements#40]
**Tested Versions:** 
Additional Placements 1.7.0-1.7.3
Minecraft 1.19.2
Forge 43.2.21

**Description:**
Vertical slabs & horizontal stairs provided by AP are missing block tags, including things like `#minecraft:mineable/pickaxe` and `#minecraft:mineable/axe`. As a result, axes do not boost harvest speed of Additional Placement wooden stairs and slabs, while Additional Placements stone slabs & stairs cannot be harvested at all.
This issue was discovered on a larger modpack, but was tested & confirmed to be present when Additional Placements was the only mod loaded.

Based on the versions affected & changelogs, I can only assume this bug was something missed during the transition to a generated datapack.

**Comment by FirEmerald** [comment]
https://github.com/FirEmerald/AdditionalPlacements/issues/31

**Comment by Xefyr0** [comment]
ye, noticed that moments before you posted. I apologize.
