### ISSUE TITLE
Generated block tag warning displays twice

### ISSUE THREAD

**Issue by Xefyr0** [FirEmerald/AdditionalPlacements#41]
**Tested Versions:**
Additional Placements 1.7.3
Minecraft 1.19.2
Forge 43.2.21

**Description:**
The warning to generate block tags displays twice when loading into a newly-generated world.
The only mod present here was Additional Placements, world was a Creative Superflat on Normal difficulty.
![doublemessage](https://github.com/FirEmerald/AdditionalPlacements/assets/78383477/8feab581-5b62-403f-ae47-220f1d7f7ce5)

On an unrelated note, I haven't seen the message *not* display when using the newer versions of Additional placements, even though the way the message is worded implies that it should only appear when dealing with unexpected combinations of tags on modded blocks. Is this intended behaviour?

**Comment by FirEmerald** [comment]
I am unsure why it does that, it did come up in testing but with no way of knowing why, I couldn't fix it. it's a relatively minor issue, though. As for the wording, if you could suggest something that sounds better, I'm all for it - the point of it is that if tag parsing notes tags on source blocks not found on the modded ones, or vice-versa, it assumes you need to regenerate the datapack

**Comment by Xefyr0** [comment]
I see. The reason I made a comment on the message's wording was because most users would assume that the mod would be able to properly deal with the vanilla blocks' tags without requiring user intervention, which it doesn't.

If there's a way to generate the tags and force a reload of the datapack whenever the message would otherwise show up, or resolve whatever is causing the modded blocks' tags to not match source blocks I think that would be a better option than just rewording the message;

an analogous situation would be someone asking you why their mechanical pencil isn't working, and you tell them that it's because they forgot to prime the spring before using it for the first time as per the instructions.
Sure, you're in the right, but that doesn't mean that the hordes of users won't be confused expecting it to "just work" like other mechanical pencils do.


Unsure if the log is helpful but I've got it anyways for reference.
[latest.log](https://github.com/FirEmerald/AdditionalPlacements/files/12504868/latest.log)

**Comment by Xefyr0** [comment]
I don't know the challenges you're facing as a mod author, though, so if you're adamant about keeping the message system as-is or simply cannot work around it then I would just replace the first sentence of the message with some sort of greeting to imply that the message and requirement of using commands on every new world is intended behavior. (which it would be)

**Comment by FirEmerald** [comment]
yeah I already decided next update will do it automatically unless a config option is turned off. the reason not to do it automatically is because the process runs in the background - it's not automatic. I figured most people would understand the message but I figured wrong.

**Comment by Xefyr0** [comment]
Yep. Users can be surprisingly obtuse - I say this having been on both sides of the equation, lol. 
Based on what you say it seems like the datapack is generated & activated as the world is loaded, but some mods manage to do it before the world generation process even begins - if you haven't already, I suggest checking out [More Compat (Wood Good)](https://github.com/MehVahdJukaar/WoodGood) and see if their method is applicable here.
