### ISSUE TITLE
you can't place slabs vertically in the latest version

### ISSUE THREAD

**Issue by 0bscureLight** [FirEmerald/AdditionalPlacements#44]
in the 1.20.1 version i found that i'm unable to place slabs vertically

**Comment by FirEmerald** [comment]
Please provide more info, such as what mods you are using. Considering the fact I have tested and found no such issue, I find it hard to believe you are running without another mod that may be conflicting, such as doubleslabs.

**Comment by 0bscureLight** [comment]
i tried with no other mod, and even the most recent suggested forge, but it was still not working

i made a video too for proof: https://www.youtube.com/watch?v=3c6iWKpNz8M

**Comment by Aerioos** [comment]
Can confirm as happening to me on Forge 47.1.3 (1.20.1).

**Comment by FirEmerald** [comment]
I identified the issue, and it's a bit of a mixin bug IMO.
fixed as of https://github.com/FirEmerald/AdditionalPlacements/commit/dc50c86109d01f0ea82290723cbbd13593ff5470
